$:
  vscode:
    - runner:
        tags: cnb:arch:amd64:gpu:H20
      docker:
        image: saltycocoa/animalorastudio-cnb:latest
      services:
        - vscode
        - docker
      stages:
        - name: setup
          script: bash setup.sh
